// This file is auto generated by flutter driver for record of pointer events.
const String scrollingRecord = r'''
[
  {
    "ts": 171694011040,
    "events": [
      {
        "timeStamp": 171693995000,
        "change": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      },
      {
        "timeStamp": 171693995000,
        "change": 4,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      }
    ]
  },
  {
    "ts": 171694023514,
    "events": [
      {
        "timeStamp": 171694011000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      }
    ]
  },
  {
    "ts": 171694027527,
    "events": [
      {
        "timeStamp": 171694020000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      }
    ]
  },
  {
    "ts": 171694064126,
    "events": [
      {
        "timeStamp": 171694029000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      }
    ]
  },
  {
    "ts": 171694065263,
    "events": [
      {
        "timeStamp": 171694038000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1943.0
      }
    ]
  },
  {
    "ts": 171694066049,
    "events": [
      {
        "timeStamp": 171694047000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1939.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694066738,
    "events": [
      {
        "timeStamp": 171694056000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1933.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694067360,
    "events": [
      {
        "timeStamp": 171694064000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1929.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694079280,
    "events": [
      {
        "timeStamp": 171694073000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1925.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694085073,
    "events": [
      {
        "timeStamp": 171694082000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1919.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694093021,
    "events": [
      {
        "timeStamp": 171694091000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1913.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694101801,
    "events": [
      {
        "timeStamp": 171694100000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 1908.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694110940,
    "events": [
      {
        "timeStamp": 171694108000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 565.0,
        "physicalY": 1904.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694121046,
    "events": [
      {
        "timeStamp": 171694117000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 563.0,
        "physicalY": 1901.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694128144,
    "events": [
      {
        "timeStamp": 171694126000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 561.0,
        "physicalY": 1895.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694136924,
    "events": [
      {
        "timeStamp": 171694135000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 558.0,
        "physicalY": 1889.0,
        "physicalDeltaX": -3.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694149083,
    "events": [
      {
        "timeStamp": 171694144000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 557.0,
        "physicalY": 1882.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694157738,
    "events": [
      {
        "timeStamp": 171694153000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 556.0,
        "physicalY": 1874.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694163688,
    "events": [
      {
        "timeStamp": 171694161000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 555.0,
        "physicalY": 1866.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694172323,
    "events": [
      {
        "timeStamp": 171694170000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 555.0,
        "physicalY": 1858.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694181279,
    "events": [
      {
        "timeStamp": 171694179000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 554.0,
        "physicalY": 1851.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694190520,
    "events": [
      {
        "timeStamp": 171694188000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 553.0,
        "physicalY": 1842.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694200859,
    "events": [
      {
        "timeStamp": 171694197000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 1833.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694208037,
    "events": [
      {
        "timeStamp": 171694206000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 1825.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694242362,
    "events": [
      {
        "timeStamp": 171694214000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 1817.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694243333,
    "events": [
      {
        "timeStamp": 171694223000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 550.0,
        "physicalY": 1807.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -10.0
      }
    ]
  },
  {
    "ts": 171694244025,
    "events": [
      {
        "timeStamp": 171694232000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 549.0,
        "physicalY": 1798.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694244575,
    "events": [
      {
        "timeStamp": 171694241000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 549.0,
        "physicalY": 1789.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694251337,
    "events": [
      {
        "timeStamp": 171694249000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 548.0,
        "physicalY": 1780.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694260170,
    "events": [
      {
        "timeStamp": 171694258000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 548.0,
        "physicalY": 1773.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694269493,
    "events": [
      {
        "timeStamp": 171694267000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 548.0,
        "physicalY": 1766.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694279957,
    "events": [
      {
        "timeStamp": 171694276000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 547.0,
        "physicalY": 1758.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694286516,
    "events": [
      {
        "timeStamp": 171694284000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1750.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694295120,
    "events": [
      {
        "timeStamp": 171694293000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1741.0,
        "physicalDeltaY": -9.0
      }
    ]
  },
  {
    "ts": 171694304112,
    "events": [
      {
        "timeStamp": 171694302000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1733.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694314250,
    "events": [
      {
        "timeStamp": 171694311000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1725.0,
        "physicalDeltaY": -8.0
      }
    ]
  },
  {
    "ts": 171694321675,
    "events": [
      {
        "timeStamp": 171694319000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 544.0,
        "physicalY": 1718.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694330571,
    "events": [
      {
        "timeStamp": 171694328000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 544.0,
        "physicalY": 1711.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694339077,
    "events": [
      {
        "timeStamp": 171694337000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 543.0,
        "physicalY": 1705.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694348353,
    "events": [
      {
        "timeStamp": 171694346000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 543.0,
        "physicalY": 1699.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694360244,
    "events": [
      {
        "timeStamp": 171694355000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 543.0,
        "physicalY": 1694.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694366370,
    "events": [
      {
        "timeStamp": 171694364000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 1689.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694374649,
    "events": [
      {
        "timeStamp": 171694372000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 1684.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694383712,
    "events": [
      {
        "timeStamp": 171694381000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 1677.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694395224,
    "events": [
      {
        "timeStamp": 171694390000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 1672.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694403925,
    "events": [
      {
        "timeStamp": 171694399000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 540.0,
        "physicalY": 1667.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694410268,
    "events": [
      {
        "timeStamp": 171694408000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 540.0,
        "physicalY": 1663.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694418880,
    "events": [
      {
        "timeStamp": 171694417000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1659.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694427700,
    "events": [
      {
        "timeStamp": 171694425000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1655.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694436577,
    "events": [
      {
        "timeStamp": 171694434000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 538.0,
        "physicalY": 1651.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694447840,
    "events": [
      {
        "timeStamp": 171694443000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 538.0,
        "physicalY": 1647.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694454464,
    "events": [
      {
        "timeStamp": 171694452000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1642.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694463243,
    "events": [
      {
        "timeStamp": 171694461000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1638.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694472080,
    "events": [
      {
        "timeStamp": 171694470000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1634.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694482620,
    "events": [
      {
        "timeStamp": 171694478000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1631.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694493251,
    "events": [
      {
        "timeStamp": 171694487000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1627.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694498555,
    "events": [
      {
        "timeStamp": 171694496000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1622.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694507203,
    "events": [
      {
        "timeStamp": 171694505000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1619.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694516617,
    "events": [
      {
        "timeStamp": 171694514000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1615.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694527581,
    "events": [
      {
        "timeStamp": 171694523000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1612.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694533485,
    "events": [
      {
        "timeStamp": 171694531000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1607.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694542156,
    "events": [
      {
        "timeStamp": 171694540000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1601.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694551330,
    "events": [
      {
        "timeStamp": 171694549000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1597.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694561668,
    "events": [
      {
        "timeStamp": 171694558000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1592.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694571935,
    "events": [
      {
        "timeStamp": 171694567000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1588.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694577958,
    "events": [
      {
        "timeStamp": 171694576000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1584.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694586838,
    "events": [
      {
        "timeStamp": 171694584000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1580.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694595383,
    "events": [
      {
        "timeStamp": 171694593000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1576.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694606047,
    "events": [
      {
        "timeStamp": 171694602000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1572.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694613039,
    "events": [
      {
        "timeStamp": 171694611000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1568.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694622382,
    "events": [
      {
        "timeStamp": 171694620000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1564.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694630726,
    "events": [
      {
        "timeStamp": 171694628000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 1561.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694639462,
    "events": [
      {
        "timeStamp": 171694637000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 538.0,
        "physicalY": 1557.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694650087,
    "events": [
      {
        "timeStamp": 171694646000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 538.0,
        "physicalY": 1554.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694656971,
    "events": [
      {
        "timeStamp": 171694655000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1550.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694666297,
    "events": [
      {
        "timeStamp": 171694664000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1547.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694675474,
    "events": [
      {
        "timeStamp": 171694673000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1544.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694683111,
    "events": [
      {
        "timeStamp": 171694681000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1540.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694694742,
    "events": [
      {
        "timeStamp": 171694690000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1535.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694701696,
    "events": [
      {
        "timeStamp": 171694699000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1530.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694710781,
    "events": [
      {
        "timeStamp": 171694708000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1526.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694719040,
    "events": [
      {
        "timeStamp": 171694717000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1521.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694729171,
    "events": [
      {
        "timeStamp": 171694725000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 1517.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694736620,
    "events": [
      {
        "timeStamp": 171694734000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 540.0,
        "physicalY": 1514.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694745104,
    "events": [
      {
        "timeStamp": 171694743000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 540.0,
        "physicalY": 1511.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694753929,
    "events": [
      {
        "timeStamp": 171694752000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 540.0,
        "physicalY": 1508.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694763212,
    "events": [
      {
        "timeStamp": 171694760000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 1505.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694774559,
    "events": [
      {
        "timeStamp": 171694769000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 1502.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694780738,
    "events": [
      {
        "timeStamp": 171694778000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 1499.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694789867,
    "events": [
      {
        "timeStamp": 171694787000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 1496.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694798628,
    "events": [
      {
        "timeStamp": 171694795000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 1493.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694810294,
    "events": [
      {
        "timeStamp": 171694804000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 1490.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694818252,
    "events": [
      {
        "timeStamp": 171694813000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 543.0,
        "physicalY": 1486.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694824140,
    "events": [
      {
        "timeStamp": 171694822000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 544.0,
        "physicalY": 1482.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694833037,
    "events": [
      {
        "timeStamp": 171694831000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 544.0,
        "physicalY": 1479.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694841490,
    "events": [
      {
        "timeStamp": 171694839000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1476.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171694851942,
    "events": [
      {
        "timeStamp": 171694848000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1472.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171694859471,
    "events": [
      {
        "timeStamp": 171694857000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1467.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694868242,
    "events": [
      {
        "timeStamp": 171694866000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1461.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694877214,
    "events": [
      {
        "timeStamp": 171694875000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1455.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694886462,
    "events": [
      {
        "timeStamp": 171694884000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1449.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694899646,
    "events": [
      {
        "timeStamp": 171694892000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1443.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694903808,
    "events": [
      {
        "timeStamp": 171694901000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1437.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694911800,
    "events": [
      {
        "timeStamp": 171694910000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1432.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694920747,
    "events": [
      {
        "timeStamp": 171694919000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1427.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694929832,
    "events": [
      {
        "timeStamp": 171694928000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1422.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694938337,
    "events": [
      {
        "timeStamp": 171694936000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1416.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694947317,
    "events": [
      {
        "timeStamp": 171694945000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1411.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694955865,
    "events": [
      {
        "timeStamp": 171694954000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1406.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171694965326,
    "events": [
      {
        "timeStamp": 171694963000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1400.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694975085,
    "events": [
      {
        "timeStamp": 171694972000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1393.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171694982973,
    "events": [
      {
        "timeStamp": 171694981000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1387.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694991532,
    "events": [
      {
        "timeStamp": 171694989000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1381.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171694999921,
    "events": [
      {
        "timeStamp": 171694998000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1375.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695009825,
    "events": [
      {
        "timeStamp": 171695007000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1369.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695020057,
    "events": [
      {
        "timeStamp": 171695016000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1364.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695026491,
    "events": [
      {
        "timeStamp": 171695025000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1360.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695035500,
    "events": [
      {
        "timeStamp": 171695033000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1357.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695044422,
    "events": [
      {
        "timeStamp": 171695042000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1353.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695053976,
    "events": [
      {
        "timeStamp": 171695051000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1350.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695064549,
    "events": [
      {
        "timeStamp": 171695060000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1346.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695070827,
    "events": [
      {
        "timeStamp": 171695069000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1343.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695079650,
    "events": [
      {
        "timeStamp": 171695078000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1340.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695088491,
    "events": [
      {
        "timeStamp": 171695086000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1337.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695098327,
    "events": [
      {
        "timeStamp": 171695095000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1335.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171695106100,
    "events": [
      {
        "timeStamp": 171695104000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1332.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695114953,
    "events": [
      {
        "timeStamp": 171695113000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1330.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171695123626,
    "events": [
      {
        "timeStamp": 171695122000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1327.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695132601,
    "events": [
      {
        "timeStamp": 171695131000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1323.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695143381,
    "events": [
      {
        "timeStamp": 171695139000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1317.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695150166,
    "events": [
      {
        "timeStamp": 171695148000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1312.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695159238,
    "events": [
      {
        "timeStamp": 171695157000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1307.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695167845,
    "events": [
      {
        "timeStamp": 171695166000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1302.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695177393,
    "events": [
      {
        "timeStamp": 171695175000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1298.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695187824,
    "events": [
      {
        "timeStamp": 171695183000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1294.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695194463,
    "events": [
      {
        "timeStamp": 171695192000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1289.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695203101,
    "events": [
      {
        "timeStamp": 171695201000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1285.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695211845,
    "events": [
      {
        "timeStamp": 171695210000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1281.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695221708,
    "events": [
      {
        "timeStamp": 171695219000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1276.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695229569,
    "events": [
      {
        "timeStamp": 171695228000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1271.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695238664,
    "events": [
      {
        "timeStamp": 171695237000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1266.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695247336,
    "events": [
      {
        "timeStamp": 171695245000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1262.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695256146,
    "events": [
      {
        "timeStamp": 171695254000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1256.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695266890,
    "events": [
      {
        "timeStamp": 171695263000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1249.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171695273643,
    "events": [
      {
        "timeStamp": 171695272000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1243.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695282579,
    "events": [
      {
        "timeStamp": 171695281000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1237.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695291575,
    "events": [
      {
        "timeStamp": 171695289000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1232.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695300894,
    "events": [
      {
        "timeStamp": 171695298000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1226.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695311372,
    "events": [
      {
        "timeStamp": 171695307000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1222.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695318212,
    "events": [
      {
        "timeStamp": 171695316000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1217.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695327062,
    "events": [
      {
        "timeStamp": 171695324000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1213.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695335784,
    "events": [
      {
        "timeStamp": 171695333000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1209.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695345793,
    "events": [
      {
        "timeStamp": 171695342000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1204.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695352730,
    "events": [
      {
        "timeStamp": 171695351000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1200.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695361657,
    "events": [
      {
        "timeStamp": 171695360000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1196.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695370988,
    "events": [
      {
        "timeStamp": 171695369000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1192.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695380241,
    "events": [
      {
        "timeStamp": 171695378000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1188.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695390842,
    "events": [
      {
        "timeStamp": 171695386000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1183.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695397668,
    "events": [
      {
        "timeStamp": 171695395000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1177.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695406743,
    "events": [
      {
        "timeStamp": 171695404000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1172.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695415347,
    "events": [
      {
        "timeStamp": 171695413000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1167.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695424436,
    "events": [
      {
        "timeStamp": 171695422000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1163.0,
        "physicalDeltaX": -1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695435043,
    "events": [
      {
        "timeStamp": 171695430000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1158.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695441834,
    "events": [
      {
        "timeStamp": 171695439000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1154.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695450622,
    "events": [
      {
        "timeStamp": 171695448000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1150.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695458510,
    "events": [
      {
        "timeStamp": 171695457000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1146.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695468174,
    "events": [
      {
        "timeStamp": 171695465000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1143.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695476241,
    "events": [
      {
        "timeStamp": 171695474000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1139.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695485262,
    "events": [
      {
        "timeStamp": 171695483000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1136.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695494747,
    "events": [
      {
        "timeStamp": 171695492000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1132.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695502341,
    "events": [
      {
        "timeStamp": 171695501000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1128.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695513901,
    "events": [
      {
        "timeStamp": 171695510000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1125.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695521059,
    "events": [
      {
        "timeStamp": 171695518000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1121.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695529998,
    "events": [
      {
        "timeStamp": 171695527000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1118.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695538729,
    "events": [
      {
        "timeStamp": 171695536000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1115.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695547516,
    "events": [
      {
        "timeStamp": 171695545000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1110.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695557635,
    "events": [
      {
        "timeStamp": 171695554000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1104.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695565098,
    "events": [
      {
        "timeStamp": 171695563000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1099.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695573562,
    "events": [
      {
        "timeStamp": 171695571000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1093.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695582728,
    "events": [
      {
        "timeStamp": 171695580000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1088.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695592423,
    "events": [
      {
        "timeStamp": 171695589000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1084.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695602935,
    "events": [
      {
        "timeStamp": 171695598000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1080.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695611703,
    "events": [
      {
        "timeStamp": 171695606000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1076.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695617851,
    "events": [
      {
        "timeStamp": 171695615000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1073.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171695626500,
    "events": [
      {
        "timeStamp": 171695624000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1068.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695637314,
    "events": [
      {
        "timeStamp": 171695633000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1064.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695644590,
    "events": [
      {
        "timeStamp": 171695642000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1060.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695653214,
    "events": [
      {
        "timeStamp": 171695650000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1056.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695661388,
    "events": [
      {
        "timeStamp": 171695659000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1052.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695670444,
    "events": [
      {
        "timeStamp": 171695668000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1047.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695682131,
    "events": [
      {
        "timeStamp": 171695677000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1042.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695688500,
    "events": [
      {
        "timeStamp": 171695686000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1035.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171695697402,
    "events": [
      {
        "timeStamp": 171695695000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1030.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695706675,
    "events": [
      {
        "timeStamp": 171695703000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1024.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695715099,
    "events": [
      {
        "timeStamp": 171695712000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 545.0,
        "physicalY": 1018.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695723074,
    "events": [
      {
        "timeStamp": 171695721000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 1012.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695732018,
    "events": [
      {
        "timeStamp": 171695730000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 547.0,
        "physicalY": 1007.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695740667,
    "events": [
      {
        "timeStamp": 171695739000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 548.0,
        "physicalY": 1003.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695749291,
    "events": [
      {
        "timeStamp": 171695747000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 998.0,
        "physicalDeltaX": 3.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695758938,
    "events": [
      {
        "timeStamp": 171695756000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 553.0,
        "physicalY": 993.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695768225,
    "events": [
      {
        "timeStamp": 171695765000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 554.0,
        "physicalY": 988.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695775932,
    "events": [
      {
        "timeStamp": 171695774000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 555.0,
        "physicalY": 984.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695784537,
    "events": [
      {
        "timeStamp": 171695783000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 555.0,
        "physicalY": 980.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695793125,
    "events": [
      {
        "timeStamp": 171695792000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 556.0,
        "physicalY": 976.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695804465,
    "events": [
      {
        "timeStamp": 171695801000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 557.0,
        "physicalY": 971.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695811587,
    "events": [
      {
        "timeStamp": 171695809000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 558.0,
        "physicalY": 965.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695820644,
    "events": [
      {
        "timeStamp": 171695818000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 559.0,
        "physicalY": 959.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695829564,
    "events": [
      {
        "timeStamp": 171695827000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 953.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695838205,
    "events": [
      {
        "timeStamp": 171695836000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 947.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695849208,
    "events": [
      {
        "timeStamp": 171695845000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 941.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695855700,
    "events": [
      {
        "timeStamp": 171695854000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 936.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695864477,
    "events": [
      {
        "timeStamp": 171695862000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 931.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695872769,
    "events": [
      {
        "timeStamp": 171695871000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 560.0,
        "physicalY": 926.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695882924,
    "events": [
      {
        "timeStamp": 171695880000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 561.0,
        "physicalY": 921.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695890525,
    "events": [
      {
        "timeStamp": 171695889000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 561.0,
        "physicalY": 917.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695899465,
    "events": [
      {
        "timeStamp": 171695898000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 562.0,
        "physicalY": 912.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695908288,
    "events": [
      {
        "timeStamp": 171695906000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 563.0,
        "physicalY": 907.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695916749,
    "events": [
      {
        "timeStamp": 171695915000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 564.0,
        "physicalY": 903.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695929392,
    "events": [
      {
        "timeStamp": 171695924000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 565.0,
        "physicalY": 898.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695934623,
    "events": [
      {
        "timeStamp": 171695933000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 566.0,
        "physicalY": 891.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -7.0
      }
    ]
  },
  {
    "ts": 171695943585,
    "events": [
      {
        "timeStamp": 171695942000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 566.0,
        "physicalY": 885.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695952366,
    "events": [
      {
        "timeStamp": 171695951000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 879.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0
      }
    ]
  },
  {
    "ts": 171695961570,
    "events": [
      {
        "timeStamp": 171695959000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 874.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171695972212,
    "events": [
      {
        "timeStamp": 171695968000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 870.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695978872,
    "events": [
      {
        "timeStamp": 171695977000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 866.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695987705,
    "events": [
      {
        "timeStamp": 171695986000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 862.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171695996573,
    "events": [
      {
        "timeStamp": 171695995000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 857.0,
        "physicalDeltaY": -5.0
      }
    ]
  },
  {
    "ts": 171696006303,
    "events": [
      {
        "timeStamp": 171696003000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 853.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171696014345,
    "events": [
      {
        "timeStamp": 171696012000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 849.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171696023146,
    "events": [
      {
        "timeStamp": 171696021000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 846.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696031681,
    "events": [
      {
        "timeStamp": 171696030000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 843.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696040523,
    "events": [
      {
        "timeStamp": 171696039000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 840.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696052039,
    "events": [
      {
        "timeStamp": 171696048000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 837.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696058214,
    "events": [
      {
        "timeStamp": 171696056000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 834.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696067355,
    "events": [
      {
        "timeStamp": 171696065000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 830.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171696076050,
    "events": [
      {
        "timeStamp": 171696074000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 826.0,
        "physicalDeltaY": -4.0
      }
    ]
  },
  {
    "ts": 171696085082,
    "events": [
      {
        "timeStamp": 171696083000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 823.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696095885,
    "events": [
      {
        "timeStamp": 171696092000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 821.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171696102651,
    "events": [
      {
        "timeStamp": 171696101000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 818.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696111394,
    "events": [
      {
        "timeStamp": 171696110000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 816.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171696120935,
    "events": [
      {
        "timeStamp": 171696118000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 814.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171696130300,
    "events": [
      {
        "timeStamp": 171696127000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 811.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696140691,
    "events": [
      {
        "timeStamp": 171696136000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 808.0,
        "physicalDeltaY": -3.0
      }
    ]
  },
  {
    "ts": 171696146809,
    "events": [
      {
        "timeStamp": 171696145000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 806.0,
        "physicalDeltaY": -2.0
      }
    ]
  },
  {
    "ts": 171696155534,
    "events": [
      {
        "timeStamp": 171696154000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 805.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696164420,
    "events": [
      {
        "timeStamp": 171696163000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 804.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696174612,
    "events": [
      {
        "timeStamp": 171696171000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 803.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696191217,
    "events": [
      {
        "timeStamp": 171696189000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 802.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696208663,
    "events": [
      {
        "timeStamp": 171696207000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 801.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696234732,
    "events": [
      {
        "timeStamp": 171696233000,
        "change": 5,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 800.0,
        "physicalDeltaY": -1.0
      }
    ]
  },
  {
    "ts": 171696252963,
    "events": [
      {
        "timeStamp": 171696249000,
        "change": 6,
        "pointerIdentifier": 1,
        "physicalX": 567.0,
        "physicalY": 800.0
      }
    ]
  }
]
''';
