// This file is auto generated by flutter driver for record of pointer events.

const String scrollingRecord = r'''
[
  {
    "ts": 83776178316,
    "events": [
      {
        "timeStamp": 83776165000,
        "change": 1,
        "signalKind": 0,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "synthesized": true,
        "pressure": 0.4173228442668915,
        "pressureMax": 1.0,
        "size": 0.031496062874794006,
        "radiusMajor": 4.0,
        "radiusMinor": 4.0
      },
      {
        "timeStamp": 83776165000,
        "change": 4,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.4173228442668915,
        "pressureMax": 1.0,
        "size": 0.031496062874794006,
        "radiusMajor": 4.0,
        "radiusMinor": 4.0
      }
    ]
  },
  {
    "ts": 83776198255,
    "events": [
      {
        "timeStamp": 83776174000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.4566929042339325,
        "pressureMax": 1.0,
        "size": 0.03543306887149811,
        "radiusMajor": 5.0,
        "radiusMinor": 4.0
      }
    ]
  },
  {
    "ts": 83776203168,
    "events": [
      {
        "timeStamp": 83776183000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.5196850299835205,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776203763,
    "events": [
      {
        "timeStamp": 83776192000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.5748031735420227,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776204236,
    "events": [
      {
        "timeStamp": 83776200000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6141732335090637,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776211595,
    "events": [
      {
        "timeStamp": 83776209000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6377952694892883,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776242808,
    "events": [
      {
        "timeStamp": 83776218000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6456692814826965,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776243199,
    "events": [
      {
        "timeStamp": 83776227000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776243462,
    "events": [
      {
        "timeStamp": 83776236000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6456692814826965,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776247664,
    "events": [
      {
        "timeStamp": 83776245000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6456692814826965,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776255756,
    "events": [
      {
        "timeStamp": 83776254000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776264546,
    "events": [
      {
        "timeStamp": 83776262000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1678.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 6.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776273450,
    "events": [
      {
        "timeStamp": 83776271000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1671.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 6.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776281818,
    "events": [
      {
        "timeStamp": 83776280000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 1662.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776292522,
    "events": [
      {
        "timeStamp": 83776289000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1651.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.6535432934761047,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776303425,
    "events": [
      {
        "timeStamp": 83776298000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1640.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.6614173054695129,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776308925,
    "events": [
      {
        "timeStamp": 83776307000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1631.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.6614173054695129,
        "pressureMax": 1.0,
        "size": 0.04330708831548691,
        "radiusMajor": 6.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776317685,
    "events": [
      {
        "timeStamp": 83776316000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1623.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.6692913174629211,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776356947,
    "events": [
      {
        "timeStamp": 83776325000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1615.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.6850393414497375,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776357776,
    "events": [
      {
        "timeStamp": 83776333000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 1607.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.6929134130477905,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776358936,
    "events": [
      {
        "timeStamp": 83776342000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 525.0,
        "physicalY": 1598.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.6929134130477905,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776359467,
    "events": [
      {
        "timeStamp": 83776351000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 523.0,
        "physicalY": 1589.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.6929134130477905,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776361852,
    "events": [
      {
        "timeStamp": 83776360000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 523.0,
        "physicalY": 1578.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776371229,
    "events": [
      {
        "timeStamp": 83776369000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1567.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776381651,
    "events": [
      {
        "timeStamp": 83776378000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1556.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776389069,
    "events": [
      {
        "timeStamp": 83776387000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1546.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.6929134130477905,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776398417,
    "events": [
      {
        "timeStamp": 83776396000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1536.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.6929134130477905,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776406839,
    "events": [
      {
        "timeStamp": 83776405000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1526.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776416173,
    "events": [
      {
        "timeStamp": 83776414000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1517.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776426888,
    "events": [
      {
        "timeStamp": 83776422000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1507.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776434272,
    "events": [
      {
        "timeStamp": 83776431000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1499.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776443070,
    "events": [
      {
        "timeStamp": 83776440000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1490.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776451606,
    "events": [
      {
        "timeStamp": 83776449000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1482.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776460816,
    "events": [
      {
        "timeStamp": 83776458000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1475.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776471919,
    "events": [
      {
        "timeStamp": 83776467000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1468.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776478240,
    "events": [
      {
        "timeStamp": 83776476000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1461.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776487396,
    "events": [
      {
        "timeStamp": 83776485000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1452.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776496120,
    "events": [
      {
        "timeStamp": 83776494000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1444.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776506816,
    "events": [
      {
        "timeStamp": 83776503000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1435.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776517024,
    "events": [
      {
        "timeStamp": 83776512000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 1426.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776522804,
    "events": [
      {
        "timeStamp": 83776520000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1416.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776532614,
    "events": [
      {
        "timeStamp": 83776529000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1407.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776541111,
    "events": [
      {
        "timeStamp": 83776538000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1400.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776550075,
    "events": [
      {
        "timeStamp": 83776547000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1393.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776562136,
    "events": [
      {
        "timeStamp": 83776556000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1384.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776567626,
    "events": [
      {
        "timeStamp": 83776565000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1375.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776576277,
    "events": [
      {
        "timeStamp": 83776574000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1366.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776585636,
    "events": [
      {
        "timeStamp": 83776583000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 1356.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776597141,
    "events": [
      {
        "timeStamp": 83776592000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 517.0,
        "physicalY": 1346.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776603329,
    "events": [
      {
        "timeStamp": 83776601000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 517.0,
        "physicalY": 1336.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776612168,
    "events": [
      {
        "timeStamp": 83776609000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1328.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776620979,
    "events": [
      {
        "timeStamp": 83776618000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1320.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776629375,
    "events": [
      {
        "timeStamp": 83776627000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1311.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776640699,
    "events": [
      {
        "timeStamp": 83776636000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1302.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776647563,
    "events": [
      {
        "timeStamp": 83776645000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1294.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776656643,
    "events": [
      {
        "timeStamp": 83776654000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 515.0,
        "physicalY": 1285.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776665363,
    "events": [
      {
        "timeStamp": 83776663000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1276.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776675388,
    "events": [
      {
        "timeStamp": 83776672000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1267.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776685336,
    "events": [
      {
        "timeStamp": 83776681000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1259.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776691716,
    "events": [
      {
        "timeStamp": 83776690000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1253.0,
        "physicalDeltaY": -6.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776700957,
    "events": [
      {
        "timeStamp": 83776698000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1246.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776709956,
    "events": [
      {
        "timeStamp": 83776707000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1237.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776719527,
    "events": [
      {
        "timeStamp": 83776716000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 1229.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776729836,
    "events": [
      {
        "timeStamp": 83776725000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1221.0,
        "physicalDeltaX": -2.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776736364,
    "events": [
      {
        "timeStamp": 83776734000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1213.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776745282,
    "events": [
      {
        "timeStamp": 83776743000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1203.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776754177,
    "events": [
      {
        "timeStamp": 83776752000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1194.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776764571,
    "events": [
      {
        "timeStamp": 83776761000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1187.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776771979,
    "events": [
      {
        "timeStamp": 83776770000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1178.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776780846,
    "events": [
      {
        "timeStamp": 83776779000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1169.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776790074,
    "events": [
      {
        "timeStamp": 83776787000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1160.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776798635,
    "events": [
      {
        "timeStamp": 83776796000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1150.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776808871,
    "events": [
      {
        "timeStamp": 83776805000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1141.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776819640,
    "events": [
      {
        "timeStamp": 83776814000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1132.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776825532,
    "events": [
      {
        "timeStamp": 83776823000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1123.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776833858,
    "events": [
      {
        "timeStamp": 83776832000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1116.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776843593,
    "events": [
      {
        "timeStamp": 83776841000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1108.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776853767,
    "events": [
      {
        "timeStamp": 83776850000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1099.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776860995,
    "events": [
      {
        "timeStamp": 83776859000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1091.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776870378,
    "events": [
      {
        "timeStamp": 83776868000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1081.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776879133,
    "events": [
      {
        "timeStamp": 83776877000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1070.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776889654,
    "events": [
      {
        "timeStamp": 83776885000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1060.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776898749,
    "events": [
      {
        "timeStamp": 83776894000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1050.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776905557,
    "events": [
      {
        "timeStamp": 83776903000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1040.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776914474,
    "events": [
      {
        "timeStamp": 83776912000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1031.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776923261,
    "events": [
      {
        "timeStamp": 83776921000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1021.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776932572,
    "events": [
      {
        "timeStamp": 83776930000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1013.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776943274,
    "events": [
      {
        "timeStamp": 83776939000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 1004.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776950981,
    "events": [
      {
        "timeStamp": 83776948000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 994.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776959014,
    "events": [
      {
        "timeStamp": 83776957000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 984.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776970282,
    "events": [
      {
        "timeStamp": 83776966000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 976.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776977200,
    "events": [
      {
        "timeStamp": 83776975000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 969.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.04724409431219101,
        "radiusMajor": 7.0,
        "radiusMinor": 5.0
      }
    ]
  },
  {
    "ts": 83776988098,
    "events": [
      {
        "timeStamp": 83776983000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 961.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83776994608,
    "events": [
      {
        "timeStamp": 83776992000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 952.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777003659,
    "events": [
      {
        "timeStamp": 83777001000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 944.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777012359,
    "events": [
      {
        "timeStamp": 83777010000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 935.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777023256,
    "events": [
      {
        "timeStamp": 83777019000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 927.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777032724,
    "events": [
      {
        "timeStamp": 83777028000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 918.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777039225,
    "events": [
      {
        "timeStamp": 83777037000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 909.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777048583,
    "events": [
      {
        "timeStamp": 83777046000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 902.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777057322,
    "events": [
      {
        "timeStamp": 83777055000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 893.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777067797,
    "events": [
      {
        "timeStamp": 83777064000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 511.0,
        "physicalY": 884.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777077318,
    "events": [
      {
        "timeStamp": 83777073000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 512.0,
        "physicalY": 875.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777083791,
    "events": [
      {
        "timeStamp": 83777082000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 512.0,
        "physicalY": 865.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7559055089950562,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777092556,
    "events": [
      {
        "timeStamp": 83777090000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 512.0,
        "physicalY": 853.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777101231,
    "events": [
      {
        "timeStamp": 83777099000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 512.0,
        "physicalY": 842.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777111531,
    "events": [
      {
        "timeStamp": 83777108000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 512.0,
        "physicalY": 833.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777122534,
    "events": [
      {
        "timeStamp": 83777117000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 513.0,
        "physicalY": 824.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777128344,
    "events": [
      {
        "timeStamp": 83777126000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 514.0,
        "physicalY": 814.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777137220,
    "events": [
      {
        "timeStamp": 83777135000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 516.0,
        "physicalY": 804.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777146330,
    "events": [
      {
        "timeStamp": 83777144000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 518.0,
        "physicalY": 794.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7559055089950562,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777157042,
    "events": [
      {
        "timeStamp": 83777153000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 519.0,
        "physicalY": 783.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7559055089950562,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777167155,
    "events": [
      {
        "timeStamp": 83777162000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 520.0,
        "physicalY": 771.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7559055089950562,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777172959,
    "events": [
      {
        "timeStamp": 83777171000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 521.0,
        "physicalY": 762.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7559055089950562,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777181840,
    "events": [
      {
        "timeStamp": 83777180000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 522.0,
        "physicalY": 752.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777192204,
    "events": [
      {
        "timeStamp": 83777189000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 523.0,
        "physicalY": 741.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777201771,
    "events": [
      {
        "timeStamp": 83777197000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 525.0,
        "physicalY": 730.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.748031497001648,
        "pressureMax": 1.0,
        "size": 0.05905511975288391,
        "radiusMajor": 8.0,
        "radiusMinor": 7.0
      }
    ]
  },
  {
    "ts": 83777208922,
    "events": [
      {
        "timeStamp": 83777206000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 526.0,
        "physicalY": 720.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777217431,
    "events": [
      {
        "timeStamp": 83777215000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 709.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777226489,
    "events": [
      {
        "timeStamp": 83777224000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 698.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777235463,
    "events": [
      {
        "timeStamp": 83777233000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 527.0,
        "physicalY": 687.0,
        "physicalDeltaY": -11.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777246440,
    "events": [
      {
        "timeStamp": 83777242000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 528.0,
        "physicalY": 675.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777256470,
    "events": [
      {
        "timeStamp": 83777251000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 528.0,
        "physicalY": 662.0,
        "physicalDeltaY": -13.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05905511975288391,
        "radiusMajor": 8.0,
        "radiusMinor": 7.0
      }
    ]
  },
  {
    "ts": 83777262302,
    "events": [
      {
        "timeStamp": 83777260000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 529.0,
        "physicalY": 650.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777270888,
    "events": [
      {
        "timeStamp": 83777269000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 530.0,
        "physicalY": 637.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -13.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777280077,
    "events": [
      {
        "timeStamp": 83777278000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 531.0,
        "physicalY": 624.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -13.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777291331,
    "events": [
      {
        "timeStamp": 83777287000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 532.0,
        "physicalY": 612.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777297431,
    "events": [
      {
        "timeStamp": 83777295000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 534.0,
        "physicalY": 600.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777306624,
    "events": [
      {
        "timeStamp": 83777304000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 537.0,
        "physicalY": 588.0,
        "physicalDeltaX": 3.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05118110030889511,
        "radiusMajor": 7.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777315562,
    "events": [
      {
        "timeStamp": 83777313000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 576.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -12.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777324402,
    "events": [
      {
        "timeStamp": 83777322000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 539.0,
        "physicalY": 566.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777336087,
    "events": [
      {
        "timeStamp": 83777331000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 541.0,
        "physicalY": 556.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -10.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777342106,
    "events": [
      {
        "timeStamp": 83777340000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 542.0,
        "physicalY": 547.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777350740,
    "events": [
      {
        "timeStamp": 83777349000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 544.0,
        "physicalY": 538.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -9.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777359676,
    "events": [
      {
        "timeStamp": 83777358000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 546.0,
        "physicalY": 530.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -8.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777370052,
    "events": [
      {
        "timeStamp": 83777366000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 548.0,
        "physicalY": 523.0,
        "physicalDeltaX": 2.0,
        "physicalDeltaY": -7.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777380017,
    "events": [
      {
        "timeStamp": 83777375000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 549.0,
        "physicalY": 517.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -6.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05905511975288391,
        "radiusMajor": 8.0,
        "radiusMinor": 7.0
      }
    ]
  },
  {
    "ts": 83777386472,
    "events": [
      {
        "timeStamp": 83777384000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 549.0,
        "physicalY": 511.0,
        "physicalDeltaY": -6.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05905511975288391,
        "radiusMajor": 8.0,
        "radiusMinor": 7.0
      }
    ]
  },
  {
    "ts": 83777395364,
    "events": [
      {
        "timeStamp": 83777393000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 550.0,
        "physicalY": 507.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -4.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05905511975288391,
        "radiusMajor": 8.0,
        "radiusMinor": 7.0
      }
    ]
  },
  {
    "ts": 83777403924,
    "events": [
      {
        "timeStamp": 83777402000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 550.0,
        "physicalY": 503.0,
        "physicalDeltaY": -4.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777414534,
    "events": [
      {
        "timeStamp": 83777411000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 550.0,
        "physicalY": 500.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777425238,
    "events": [
      {
        "timeStamp": 83777420000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 550.0,
        "physicalY": 497.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7401574850082397,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777430713,
    "events": [
      {
        "timeStamp": 83777429000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 494.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777439542,
    "events": [
      {
        "timeStamp": 83777437000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 492.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777448537,
    "events": [
      {
        "timeStamp": 83777446000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 489.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777459342,
    "events": [
      {
        "timeStamp": 83777455000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 486.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777466485,
    "events": [
      {
        "timeStamp": 83777464000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 482.0,
        "physicalDeltaY": -4.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777475273,
    "events": [
      {
        "timeStamp": 83777473000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 479.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777483872,
    "events": [
      {
        "timeStamp": 83777482000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 477.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777493452,
    "events": [
      {
        "timeStamp": 83777490000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 475.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777503537,
    "events": [
      {
        "timeStamp": 83777499000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 473.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7007874250411987,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777510421,
    "events": [
      {
        "timeStamp": 83777508000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 470.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7086614370346069,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777519234,
    "events": [
      {
        "timeStamp": 83777517000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 551.0,
        "physicalY": 468.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777527999,
    "events": [
      {
        "timeStamp": 83777526000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 465.0,
        "physicalDeltaX": 1.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7165354490280151,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777537738,
    "events": [
      {
        "timeStamp": 83777535000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 461.0,
        "physicalDeltaY": -4.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777548213,
    "events": [
      {
        "timeStamp": 83777544000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 458.0,
        "physicalDeltaY": -3.0,
        "pressure": 0.7244094610214233,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777554432,
    "events": [
      {
        "timeStamp": 83777552000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 456.0,
        "physicalDeltaY": -2.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777563826,
    "events": [
      {
        "timeStamp": 83777561000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 455.0,
        "physicalDeltaY": -1.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777572330,
    "events": [
      {
        "timeStamp": 83777570000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 454.0,
        "physicalDeltaY": -1.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777585310,
    "events": [
      {
        "timeStamp": 83777579000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 453.0,
        "physicalDeltaY": -1.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777598774,
    "events": [
      {
        "timeStamp": 83777597000,
        "change": 5,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 452.0,
        "physicalDeltaY": -1.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  },
  {
    "ts": 83777667947,
    "events": [
      {
        "timeStamp": 83777665000,
        "change": 6,
        "signalKind": 0,
        "pointerIdentifier": 1,
        "physicalX": 552.0,
        "physicalY": 452.0,
        "pressure": 0.7322834730148315,
        "pressureMax": 1.0,
        "size": 0.05511811003088951,
        "radiusMajor": 8.0,
        "radiusMinor": 6.0
      }
    ]
  }
]
''';
